In [4]:
#cargar las librerias 

import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd
import seaborn as sns
import openpyxl as pxl

In [5]:
#cargamos el dataset
data = pd.read_excel('data_academic_performance.xlsx')  
data.head()

,COD_S11,GENDER,EDU_FATHER,EDU_MOTHER,OCC_FATHER,OCC_MOTHER,STRATUM,SISBEN,PEOPLE_HOUSE,Unnamed: 9,...,CC_PRO,ENG_PRO,WC_PRO,FEP_PRO,G_SC,PERCENTILE,2ND_DECILE,QUARTILE,SEL,SEL_IHE
0,SB11201210000129,F,Incomplete Professional Education,Complete technique or technology,Technical or professional level employee,Home,Stratum 4,It is not classified by the SISBEN,Three,NaN,...,71,93,79,181,180,91,5,4,2,2
1,SB11201210000137,F,Complete Secundary,Complete professional education,Entrepreneur,Independent professional,Stratum 5,It is not classified by the SISBEN,Three,NaN,...,86,98,78,201,182,92,5,4,4,4
2,SB11201210005154,M,Not sure,Not sure,Independent,Home,Stratum 2,Level 2,Five,NaN,...,18,43,22,113,113,7,1,1,1,1
3,SB11201210007504,F,Not sure,Not sure,Other occupation,Independent,Stratum 2,It is not classified by the SISBEN,Three,NaN,...,76,80,48,137,157,67,4,3,2,2
4,SB11201210007548,M,Complete professional education,Complete professional education,Executive,Home,Stratum 4,It is not classified by the SISBEN,One,NaN,...,98,100,71,189,198,98,5,4,4,2

In [6]:
data.info()
data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12411 entries, 0 to 12410
Data columns (total 45 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   COD_S11           12411 non-null  object
 1   GENDER            12411 non-null  object
 2   EDU_FATHER        12411 non-null  object
 3   EDU_MOTHER        12411 non-null  object
 4   OCC_FATHER        12411 non-null  object
 5   OCC_MOTHER        12411 non-null  object
 6   STRATUM           12411 non-null  object
 7   SISBEN            12411 non-null  object
 8   PEOPLE_HOUSE      12411 non-null  object
 9   Unnamed: 9        0 non-null      float64
 10  INTERNET          12411 non-null  object
 11  TV                12411 non-null  object
 12  COMPUTER          12411 non-null  object
 13  WASHING_MCH       12411 non-null  object
 14  MIC_OVEN          12411 non-null  object
 15  CAR               12411 non-null  object
 16  DVD               12411 non-null  object
 17  FRESH             12411 non-null  object
 18  PHONE             12411 non-null  object
 19  MOBILE            12411 non-null  object
 20  REVENUE           12411 non-null  object
 21  JOB               12411 non-null  object
 22  SCHOOL_NAME       12411 non-null  object
 23  SCHOOL_NAT        12411 non-null  object
 24  SCHOOL_TYPE       12411 non-null  object
 25  MAT_S11           12411 non-null  int64
 26  CR_S11            12411 non-null  int64
 27  CC_S11            12411 non-null  int64
 28  BIO_S11           12411 non-null  int64
 29  ENG_S11           12411 non-null  int64
 30  Cod_SPro          12411 non-null  object
 31  UNIVERSITY        12411 non-null  object
 32  ACADEMIC_PROGRAM  12411 non-null  object
 33  QR_PRO            12411 non-null  int64
 34  CR_PRO            12411 non-null  int64
 35  CC_PRO            12411 non-null  int64
 36  ENG_PRO           12411 non-null  int64
 37  WC_PRO            12411 non-null  int64
 38  FEP_PRO           12411 non-null  int64
 39  G_SC              12411 non-null  int64
 40  PERCENTILE        12411 non-null  int64
 41  2ND_DECILE        12411 non-null  int64
 42  QUARTILE          12411 non-null  int64
 43  SEL               12411 non-null  int64
 44  SEL_IHE           12411 non-null  int64
dtypes: float64(1), int64(17), object(27)
memory usage: 4.3+ MB

,Unnamed: 9,MAT_S11,CR_S11,CC_S11,BIO_S11,ENG_S11,QR_PRO,CR_PRO,CC_PRO,ENG_PRO,WC_PRO,FEP_PRO,G_SC,PERCENTILE,2ND_DECILE,QUARTILE,SEL,SEL_IHE
count,0.0,12411.000000,12411.000000,12411.000000,12411.000000,12411.000000,12411.000000,12411.000000,12411.00000,12411.000000,12411.000000,12411.000000,12411.000000,12411.000000,12411.000000,12411.000000,12411.000000,12411.000000
mean,NaN,64.320764,60.778422,60.705181,63.950528,61.801064,77.417291,62.199339,59.18677,67.498348,53.703408,145.476593,162.710499,68.446459,3.885747,3.188865,2.598904,2.409395
std,NaN,11.873650,10.025876,10.120524,11.156869,14.297777,22.673444,27.666558,28.99184,25.495096,30.001734,40.126386,23.112479,25.867550,1.248431,0.979043,1.111704,0.926765
min,NaN,26.000000,24.000000,0.000000,11.000000,26.000000,1.000000,1.000000,1.00000,1.000000,0.000000,1.000000,37.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,NaN,56.000000,54.000000,54.000000,56.000000,50.000000,65.000000,42.000000,36.00000,51.000000,28.000000,124.000000,147.000000,51.000000,3.000000,3.000000,2.000000,2.000000
50%,NaN,64.000000,61.000000,60.000000,64.000000,59.000000,85.000000,67.000000,65.00000,74.000000,56.000000,153.000000,163.000000,75.000000,4.000000,4.000000,2.000000,2.000000
75%,NaN,72.000000,67.000000,67.000000,71.000000,72.000000,96.000000,86.000000,85.00000,88.000000,80.000000,174.000000,179.000000,90.000000,5.000000,4.000000,4.000000,3.000000
max,NaN,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,300.000000,247.000000,100.000000,5.000000,4.000000,4.000000,4.000000

In [7]:
#ver columnas con Nans
data.isnull().sum()

COD_S11                 0
GENDER                  0
EDU_FATHER              0
EDU_MOTHER              0
OCC_FATHER              0
OCC_MOTHER              0
STRATUM                 0
SISBEN                  0
PEOPLE_HOUSE            0
Unnamed: 9          12411
INTERNET                0
TV                      0
COMPUTER                0
WASHING_MCH             0
MIC_OVEN                0
CAR                     0
DVD                     0
FRESH                   0
PHONE                   0
MOBILE                  0
REVENUE                 0
JOB                     0
SCHOOL_NAME             0
SCHOOL_NAT              0
SCHOOL_TYPE             0
MAT_S11                 0
CR_S11                  0
CC_S11                  0
BIO_S11                 0
ENG_S11                 0
Cod_SPro                0
UNIVERSITY              0
ACADEMIC_PROGRAM        0
QR_PRO                  0
CR_PRO                  0
CC_PRO                  0
ENG_PRO                 0
WC_PRO                  0
FEP_PRO                 0
G_SC                    0
PERCENTILE              0
2ND_DECILE              0
QUARTILE                0
SEL                     0
SEL_IHE                 0
dtype: int64

In [8]:
#eliminamos columna unmamed: 9 (si existe)
if 'Unnamed: 9' in data.columns:
    data = data.drop(columns=['Unnamed: 9'])

data.isnull().sum()

COD_S11             0
GENDER              0
EDU_FATHER          0
EDU_MOTHER          0
OCC_FATHER          0
OCC_MOTHER          0
STRATUM             0
SISBEN              0
PEOPLE_HOUSE        0
INTERNET            0
TV                  0
COMPUTER            0
WASHING_MCH         0
MIC_OVEN            0
CAR                 0
DVD                 0
FRESH               0
PHONE               0
MOBILE              0
REVENUE             0
JOB                 0
SCHOOL_NAME         0
SCHOOL_NAT          0
SCHOOL_TYPE         0
MAT_S11             0
CR_S11              0
CC_S11              0
BIO_S11             0
ENG_S11             0
Cod_SPro            0
UNIVERSITY          0
ACADEMIC_PROGRAM    0
QR_PRO              0
CR_PRO              0
CC_PRO              0
ENG_PRO             0
WC_PRO              0
FEP_PRO             0
G_SC                0
PERCENTILE          0
2ND_DECILE          0
QUARTILE            0
SEL                 0
SEL_IHE             0
dtype: int64

In [9]:
#separamos columnas categoricas y numericas
data_categoricas = data.select_dtypes(include=['object'])
data_numericas = data.select_dtypes(include=['number'])

data_numericas.head()

,MAT_S11,CR_S11,CC_S11,BIO_S11,ENG_S11,QR_PRO,CR_PRO,CC_PRO,ENG_PRO,WC_PRO,FEP_PRO,G_SC,PERCENTILE,2ND_DECILE,QUARTILE,SEL,SEL_IHE
0,71,81,61,86,82,71,93,71,93,79,181,180,91,5,4,2,2
1,83,75,66,100,88,97,38,86,98,78,201,182,92,5,4,4,4
2,52,49,38,46,42,17,1,18,43,22,113,113,7,1,1,1,1
3,56,55,51,64,73,65,35,76,80,48,137,157,67,4,3,2,2
4,80,65,76,85,92,94,94,98,100,71,189,198,98,5,4,4,2

In [10]:
data_categoricas.head()

,COD_S11,GENDER,EDU_FATHER,EDU_MOTHER,OCC_FATHER,OCC_MOTHER,STRATUM,SISBEN,PEOPLE_HOUSE,INTERNET,...,PHONE,MOBILE,REVENUE,JOB,SCHOOL_NAME,SCHOOL_NAT,SCHOOL_TYPE,Cod_SPro,UNIVERSITY,ACADEMIC_PROGRAM
0,SB11201210000129,F,Incomplete Professional Education,Complete technique or technology,Technical or professional level employee,Home,Stratum 4,It is not classified by the SISBEN,Three,Yes,...,Yes,Yes,Between 1 and less than 2 LMMW,No,COL NUEVO CAMBRIDGE,PRIVATE,ACADEMIC,EK201830142293,UNIVERSIDAD DE SANTANDER - UDES-BUCARAMANGA,INDUSTRIAL ENGINEERING
1,SB11201210000137,F,Complete Secundary,Complete professional education,Entrepreneur,Independent professional,Stratum 5,It is not classified by the SISBEN,Three,Yes,...,Yes,Yes,10 or more LMMW,No,COL LA QUINTA DEL PUENTE,PRIVATE,ACADEMIC,EK201830002633,UNIVERSIDAD DE LOS ANDES-BOGOTÁ D.C.,INDUSTRIAL ENGINEERING
2,SB11201210005154,M,Not sure,Not sure,Independent,Home,Stratum 2,Level 2,Five,No,...,Yes,No,Between 1 and less than 2 LMMW,"Yes, 20 hours or more per week",CENT EDUC PAULO FREIRE ...,PRIVATE,ACADEMIC,EK201830196510,UNIVERSIDAD NACIONAL ABIERTA Y A DISTANCIA UNA...,ELECTRONIC ENGINEERING
3,SB11201210007504,F,Not sure,Not sure,Other occupation,Independent,Stratum 2,It is not classified by the SISBEN,Three,Yes,...,Yes,Yes,Between 2 and less than 3 LMMW,No,LICEO ANDINO,PRIVATE,ACADEMIC,EK201830031665,UNIVERSIDAD CATOLICA DE PEREIRA-PEREIRA,INDUSTRIAL ENGINEERING
4,SB11201210007548,M,Complete professional education,Complete professional education,Executive,Home,Stratum 4,It is not classified by the SISBEN,One,Yes,...,Yes,Yes,Between 7 and less than 10 LMMW,No,LIC TALLER SAN MIGUEL,PRIVATE,ACADEMIC,EK201830130461,UNIVERSIDAD INDUSTRIAL DE SANTANDER-BUCARAMANGA,INDUSTRIAL ENGINEERING

In [11]:
data['REVENUE'].value_counts()

REVENUE
Between 1 and less than 2 LMMW     3873
Between 2 and less than 3 LMMW     2783
Between 3 and less than 5 LMMW     2239
less than 1 LMMW                   1037
Between 5 and less than 7 LMMW      973
10 or more LMMW                     718
Between 7 and less than 10 LMMW     509
0                                   279
Name: count, dtype: int64

In [15]:
# Definir un mapeo
orden = {'less than 1 LMMW': 1, 'Between 1 and less than 2 LMMW': 2, 'Between 2 and less than 3 LMMW': 3, 'Between 3 and less than 5 LMMW': 4, 'Between 5 and less than 7 LMMW': 5, 'Between 7 and less than 10 LMMW': 6, '10 or more LMMW': 7}

# Aplicar el mapeo personalizado
data['REVENUE'] = data['REVENUE'].map(orden)

In [ ]:
data['REVENUE'].value_counts()

REVENUE
2.0    3873
3.0    2783
4.0    2239
1.0    1037
5.0     973
7.0     718
6.0     509
Name: count, dtype: int64